image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - docker info
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose

stages:
  - test
  - docker_cleanup

Test:
  stage: test
  script:
    - make test

Docker_Cleanup:
  stage: docker_cleanup
  script:
    - make docker_cleanup
  when: always