version: '3.7'

services:
  testing_db:
    image: postgres:9.6
    container_name: develoship_website_testing_db
    restart: on-failure
    environment:
      POSTGRES_DB: develoship_website_testing_db
      POSTGRES_USER: website_user
      POSTGRES_PASSWORD: xTn6nCt6ya
    networks:
    - website_testing_net

  backend_tests:
    image: backend_tests
    environment:
      DJANGO_SECRET_KEY: Xkf/6#'1{+Y.xgR
      DATABASE_URL: postgres://website_user:xTn6nCt6ya@db/develoship_website_testing_db
    build: .
    depends_on:
      - testing_db
    command: python /code/manage.py test
    networks:
    - website_testing_net

networks:
  website_testing_net:
    driver: bridge