# Generated by Django 2.1.7 on 2019-03-04 06:56

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='excerpt',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
