version: '3.7'

services:
  db:
    container_name: develoship_website_testing_db
    environment:
      POSTGRES_DB: develoship_website_testing_db
      POSTGRES_USER: website_user
      POSTGRES_PASSWORD: xTn6nCt6ya
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch:2.3
    restart: always
    expose:
      - "9200"

  app:
    image: develoship_website_testing
    container_name: develoship_website_testing
    environment:
      DJANGO_SECRET_KEY: Xkf/6#'1{+Y.xgR
      DATABASE_URL: postgres://website_user:xTn6nCt6ya@db/develoship_website_testing_db
      CACHE_URL: redis://redis
      ELASTICSEARCH_ENDPOINT: elasticsearch
    build:
      context: ..
      dockerfile: Dockerfile
    links:
      - db:db
      - redis:redis
      - elasticsearch:elasticsearch
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - elasticsearch
    command: python /code/manage.py test
